# Generated by Django 6.0.2 on 2026-02-26 05:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('punds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('pund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='punds.pund')),
            ],
        ),
        migrations.CreateModel(
            name='PundStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_interest_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('missed_week_penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='punds.pund')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
