# Generated by Django 6.0.2 on 2026-02-27 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-cycle_number'],
            },
        ),
        migrations.CreateModel(
            name='PundStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_interest_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('missed_saving_penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('missed_loan_penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_loan_cycles', models.IntegerField(default=10)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
