# Generated by Django 6.0.2 on 2026-02-26 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('punds', '0002_remove_pund_saving_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-week_number']},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('pund', 'member', 'week_number')},
        ),
    ]
