# Generated by Django 6.0.2 on 2026-02-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_payment_options_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
