# Generated by Django 6.0.2 on 2026-02-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pund',
            name='saving_amount',
        ),
    ]
