# Generated by Django 4.2.29 on 2026-03-07 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "interest_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("total_payable", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_cycles", models.IntegerField()),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("cycle_number", models.IntegerField()),
                ("emi_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "penalty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("due_date", models.DateField()),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["cycle_number"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_number", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "penalty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-cycle_number"],
            },
        ),
        migrations.CreateModel(
            name="PundStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saving_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "loan_interest_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "missed_saving_penalty",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "missed_loan_penalty",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("default_loan_cycles", models.IntegerField(default=10)),
                ("effective_from", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
    ]
