# Generated by Django 4.2.29 on 2026-03-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("punds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pundstructure",
            name="pund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="punds.pund"
            ),
        ),
    ]
