# Generated by Django 6.0.2 on 2026-02-27 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('punds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='pund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='punds.pund'),
        ),
        migrations.AddField(
            model_name='pundstructure',
            name='pund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punds.pund'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('pund', 'member', 'cycle_number')},
        ),
    ]
