# Generated by Django 4.2.29 on 2026-03-07 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0002_initial"),
        ("punds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="pund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="punds.pund",
            ),
        ),
        migrations.AddField(
            model_name="loaninstallment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installments",
                to="finance.loan",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="pund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="punds.pund"
            ),
        ),
        migrations.AddField(
            model_name="financeauditlog",
            name="pund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="punds.pund"
            ),
        ),
        migrations.AddField(
            model_name="financeauditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("pund", "member", "cycle_number")},
        ),
        migrations.AlterUniqueTogether(
            name="loaninstallment",
            unique_together={("loan", "cycle_number")},
        ),
    ]
