# Generated by Django 4.2.29 on 2026-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("SAVING", "Saving"),
                    ("EMI", "Loan EMI"),
                    ("PENALTY", "Penalty"),
                ],
                default="SAVING",
                max_length=20,
            ),
        ),
    ]
