# Generated by Django 4.2.29 on 2026-03-13 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("punds", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0004_payment_payment_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="payment",
            unique_together={("pund", "member", "cycle_number", "payment_type")},
        ),
    ]
