# Generated by Django 6.0.2 on 2026-03-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financeauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninstallment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
    ]
